// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20241026184547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Dogadjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DogadjajKategorijaId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Objavio")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("VrijemePocetka")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajKategorijaId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("Core.Entities.DogadjajKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DogadjajKategorije");
                });

            modelBuilder.Entity("Core.Entities.Fajl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Core.Entities.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("boolean");

                    b.Property<int>("BrojPolaznika")
                        .HasColumnType("integer");

                    b.Property<double>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("KratakOpis")
                        .HasColumnType("text");

                    b.Property<int>("KursKategorijaId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Objavio")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<int>("Trajanje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KursKategorijaId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Kursevi");
                });

            modelBuilder.Entity("Core.Entities.KursKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KursKategorije");
                });

            modelBuilder.Entity("Core.Entities.Obuka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("boolean");

                    b.Property<int>("BrojPolaznika")
                        .HasColumnType("integer");

                    b.Property<double>("Cijena")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("KratakOpis")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Objavio")
                        .HasColumnType("text");

                    b.Property<int>("ObukaKategorijaId")
                        .HasColumnType("integer");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<int>("Trajanje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObukaKategorijaId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Obuke");
                });

            modelBuilder.Entity("Core.Entities.ObukaKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ObukaKategorije");
                });

            modelBuilder.Entity("Core.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("text");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Tiktok")
                        .HasColumnType("text");

                    b.Property<string>("Twitter")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Web")
                        .HasColumnType("text");

                    b.Property<string>("Youtube")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("Partneri");
                });

            modelBuilder.Entity("Core.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Core.Entities.Prijava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<int?>("KursId")
                        .HasColumnType("integer");

                    b.Property<string>("Objava")
                        .HasColumnType("text");

                    b.Property<int?>("ObukaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Pogledano")
                        .HasColumnType("boolean");

                    b.Property<string>("PrethodnoZnanje")
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Zanimanje")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("ObukaId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("Core.Entities.Publikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumObjavljivanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FajlId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Objavio")
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FajlId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Publikacije");
                });

            modelBuilder.Entity("Core.Entities.Vijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Fokus")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Naslov")
                        .HasColumnType("text");

                    b.Property<string>("Objavio")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("Podnaslov")
                        .HasColumnType("text");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("text");

                    b.Property<int>("VijestKategorijaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("VijestKategorijaId");

                    b.ToTable("Vijesti");
                });

            modelBuilder.Entity("Core.Entities.VijestKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VijestKategorije");
                });

            modelBuilder.Entity("Core.Entities.Dogadjaj", b =>
                {
                    b.HasOne("Core.Entities.DogadjajKategorija", "DogadjajKategorija")
                        .WithMany()
                        .HasForeignKey("DogadjajKategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("DogadjajKategorija");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Kurs", b =>
                {
                    b.HasOne("Core.Entities.KursKategorija", "KursKategorija")
                        .WithMany()
                        .HasForeignKey("KursKategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("KursKategorija");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Obuka", b =>
                {
                    b.HasOne("Core.Entities.ObukaKategorija", "ObukaKategorija")
                        .WithMany()
                        .HasForeignKey("ObukaKategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("ObukaKategorija");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Partner", b =>
                {
                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Prijava", b =>
                {
                    b.HasOne("Core.Entities.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId");

                    b.HasOne("Core.Entities.Obuka", "Obuka")
                        .WithMany()
                        .HasForeignKey("ObukaId");

                    b.Navigation("Kurs");

                    b.Navigation("Obuka");
                });

            modelBuilder.Entity("Core.Entities.Publikacija", b =>
                {
                    b.HasOne("Core.Entities.Fajl", "Fajl")
                        .WithMany()
                        .HasForeignKey("FajlId");

                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("Fajl");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Core.Entities.Vijest", b =>
                {
                    b.HasOne("Core.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("Core.Entities.VijestKategorija", "VijestKategorija")
                        .WithMany()
                        .HasForeignKey("VijestKategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("VijestKategorija");
                });
#pragma warning restore 612, 618
        }
    }
}
